# Generated by Django 3.2.5 on 2021-07-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='start date of reservation')),
                ('date_to', models.DateField(verbose_name='end date of reservation')),
                ('name', models.CharField(max_length=100, verbose_name='name of the person who made reservation')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotel.reservation'),
        ),
    ]
