# Generated by Django 3.2.5 on 2021-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210723_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservation',
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ManyToManyField(related_name='rooms', to='hotel.Reservation'),
        ),
    ]
