# Generated by Django 3.2.5 on 2021-07-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210723_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='reservation',
            new_name='reservations',
        ),
    ]
