# Generated by Django 3.2.5 on 2021-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_rename_reservation_room_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(related_name='reservations', to='hotel.Room'),
        ),
    ]
