# Generated by Django 3.2.5 on 2021-07-27 12:59

from django.db import migrations
from django.contrib.auth.models import Group


def create_staff_group(apps, schema_editor):
    Group.objects.create(name='staff')


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_reservation_owner'),
    ]

    operations = [
        migrations.RunPython(create_staff_group)
    ]
